<a href="https://colab.research.google.com/github/luthfijuliandri/Intelligence-System/blob/main/Tugas_IS_RK_Muhammad_Luthfi_Juliandri_4521210078.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tugas Intelligence System**
## Nama : Muhammad Luthfi Juliandri
## NPM  : 4521210078

![gambar_2024-10-07_012337782.png]()

Import library pandas dan mlxtend untuk penggunaan apriori dan aturan asosiasi

In [56]:
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

Definisikan dataset menggunakan array berdasarkan soal yang diberikan

In [57]:
dataset = [['Telur', 'Beras'],
           ['Telur', 'Beras', 'Minyak', 'Topi'],
           ['Telur', 'Beras', 'Minyak', 'Buku'],
           ['Buku', 'Minyak', 'Topi'],
           ['Telur', 'Beras', 'Minyak', 'Topi'],
           ['Telur', 'Beras', 'Minyak'],
           ['Telur', 'Minyak', 'Buku'],
           ['Beras', 'Buku'],
         ]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [58]:
dataset

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

[['Telur', 'Beras'],
 ['Telur', 'Beras', 'Minyak', 'Topi'],
 ['Telur', 'Beras', 'Minyak', 'Buku'],
 ['Buku', 'Minyak', 'Topi'],
 ['Telur', 'Beras', 'Minyak', 'Topi'],
 ['Telur', 'Beras', 'Minyak'],
 ['Telur', 'Minyak', 'Buku'],
 ['Beras', 'Buku']]

Memakai TransactionEncoder agar array dataset di convert ke dataframe

In [59]:
te = TransactionEncoder()
te_array = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_array, columns=te.columns_)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [60]:
df

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

   Beras   Buku  Minyak  Telur   Topi
0   True  False   False   True  False
1   True  False    True   True   True
2   True   True    True   True  False
3  False   True    True  False   True
4   True  False    True   True   True
5   True  False    True   True  False
6  False   True    True   True  False
7   True   True   False  False  False

# **Implementasi Apriori**

Menggunakan library apriori untuk melakukan perhitungan frequent item set. Nilai minimum (ɸ = 2), Sehingga min supportnya adalah **2/8 = 0.25**

In [61]:
frequent_itemsets = apriori(df, min_support=0.25, use_colnames=True)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [62]:
frequent_itemsets

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

    support                      itemsets
0     0.750                       (Beras)
1     0.500                        (Buku)
2     0.750                      (Minyak)
3     0.750                       (Telur)
4     0.375                        (Topi)
5     0.250                 (Buku, Beras)
6     0.500               (Beras, Minyak)
7     0.625                (Beras, Telur)
8     0.250                 (Beras, Topi)
9     0.375                (Buku, Minyak)
10    0.250                 (Buku, Telur)
11    0.625               (Telur, Minyak)
12    0.375                (Topi, Minyak)
13    0.250                 (Telur, Topi)
14    0.500        (Beras, Telur, Minyak)
15    0.250         (Beras, Minyak, Topi)
16    0.250          (Beras, Telur, Topi)
17    0.250         (Buku, Telur, Minyak)
18    0.250         (Topi, Telur, Minyak)
19    0.250  (Beras, Telur, Minyak, Topi)

*Dilakukan sampai dengan F4. Dengan demikian F4 adalah (Beras, Telur, Minyak, Topi) karena hanya kombinasi inilah yang memenuhi syarat minimal support yang ditentukan.*

## **Implementasi Aturan Asosiasi**

Menggunakan library association_rules untuk melakukan perhitungan aturan asosiasi dengan confidence minimum 60% atau 0.6.

In [63]:
res = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.6)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [64]:
res

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(Beras),(Minyak),0.750,0.750,0.500,0.666667,0.888889,-0.062500,0.750,-0.333333
1,(Minyak),(Beras),0.750,0.750,0.500,0.666667,0.888889,-0.062500,0.750,-0.333333
2,(Beras),(Telur),0.750,0.750,0.625,0.833333,1.111111,0.062500,1.500,0.400000
3,(Telur),(Beras),0.750,0.750,0.625,0.833333,1.111111,0.062500,1.500,0.400000
4,(Topi),(Beras),0.375,0.750,0.250,0.666667,0.888889,-0.031250,0.750,-0.166667
5,(Buku),(Minyak),0.500,0.750,0.375,0.750000,1.000000,0.000000,1.000,0.000000
6,(Telur),(Minyak),0.750,0.750,0.625,0.833333,1.111111,0.062500,1.500,0.400000
7,(Minyak),(Telur),0.750,0.750,0.625,0.833333,1.111111,0.062500,1.500,0.400000
8,(Topi),(Minyak),0.375,0.750,0.375,1.000000,1.333333,0.093750,inf,0.400000
9,(Topi),(Telur),0.375,0.750,0.250,0.666667,0.888889,-0.031250,0.750,-0.166667
10,"(Beras, Telur)",(Minyak),0.625,0.750,0.500,0.800000,1.066667,0.031250,1.250,0.166667
11,"(Beras, Minyak)",(Telur),0.500,0.750,0.500,1.000000,1.333333,0.125000,inf,0.500000
12,"(Telur, Minyak)",(Beras),0.625,0.750,0.500,0.800000,1.066667,0.031250,1.250,0.166667
13,(Beras),"(Telur, Minyak)",0.750,0.625,0.500,0.666667,1.066667,0.031250,1.125,0.250000
14,(Telur),"(Beras, Minyak)",0.750,0.500,0.500,0.666667,1.333333,0.125000,1.500,1.000000
15,(Minyak),"(Beras, Telur)",0.750,0.625,0.500,0.666667,1.066667,0.031250,1.125,0.250000
16,"(Beras, Topi)",(Minyak),0.250,0.750,0.250,1.000000,1.333333,0.062500,inf,0.333333
17,"(Topi, Minyak)",(Beras),0.375,0.750,0.250,0.666667,0.888889,-0.031250,0.750,-0.166667
18,(Topi),"(Beras, Minyak)",0.375,0.500,0.250,0.666667,1.333333,0.062500,1.500,0.400000
19,"(Beras, Topi)",(Telur),0.250,0.750,0.250,1.000000,1.333333,0.062500,inf,0.333333
20,"(Telur, Topi)",(Beras),0.250,0.750,0.250,1.000000,1.333333,0.062500,inf,0.333333
21,(Topi),"(Beras, Telur)",0.375,0.625,0.250,0.666667,1.066667,0.015625,1.125,0.100000
22,"(Buku, Telur)",(Minyak),0.250,0.750,0.250,1.000000,1.333333,0.062500,inf,0.333333
23,"(Buku, Minyak)",(Telur),0.375,0.750,0.250,0.666667,0.888889,-0.031250,0.750,-0.166667
24,"(Telur, Topi)",(Minyak),0.250,0.750,0.250,1.000000,1.333333,0.062500,inf,0.333333
25,"(Minyak, Topi)",(Telur),0.375,0.750,0.250,0.666667,0.888889,-0.031250,0.750,-0.166667
26,(Topi),"(Telur, Minyak)",0.375,0.625,0.250,0.666667,1.066667,0.015625,1.125,0.100000
27,"(Beras, Telur, Topi)",(Minyak),0.250,0.750,0.250,1.000000,1.333333,0.062500,inf,0.333333
28,"(Beras, Minyak, Topi)",(Telur),0.250,0.750,0.250,1.000000,1.333333,0.062500,inf,0.333333
29,"(Topi, Telur, Minyak)",(Beras),0.250,0.750,0.250,1.000000,1.333333,0.062500,inf,0.333333
30,"(Beras, Topi)","(Telur, Minyak)",0.250,0.625,0.250,1.000000,1.600000,0.093750,inf,0.500000
31,"(Telur, Topi)","(Beras, Minyak)",0.250,0.500,0.250,1.000000,2.000000,0.125000,inf,0.666667
32,"(Topi, Minyak)","(Beras, Telur)",0.375,0.625,0.250,0.666667,1.066667,0.015625,1.125,0.100000
33,(Topi),"(Beras, Telur, Minyak)",0.375,0.500,0.250,0.666667,1.333333,0.062500,1.500,0.400000

Hasil dari association rule di rapikan sehingga kolom yang muncul hanya antecendents consequent support confidence dan lift.

### Aturan Asosisasi Final

Mencari nilai akhir dengan mengkalikan support dan confidence.

In [69]:
res['supportxconfidence'] = res['support'] * res['confidence']
res_sort= res[['antecedents', 'consequents', 'support', 'confidence', 'supportxconfidence']]

res_sort

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,antecedents,consequents,support,confidence,supportxconfidence
0,(Beras),(Minyak),0.500,0.666667,0.333333
1,(Minyak),(Beras),0.500,0.666667,0.333333
2,(Beras),(Telur),0.625,0.833333,0.520833
3,(Telur),(Beras),0.625,0.833333,0.520833
4,(Topi),(Beras),0.250,0.666667,0.166667
5,(Buku),(Minyak),0.375,0.750000,0.281250
6,(Telur),(Minyak),0.625,0.833333,0.520833
7,(Minyak),(Telur),0.625,0.833333,0.520833
8,(Topi),(Minyak),0.375,1.000000,0.375000
9,(Topi),(Telur),0.250,0.666667,0.166667
10,"(Beras, Telur)",(Minyak),0.500,0.800000,0.400000
11,"(Beras, Minyak)",(Telur),0.500,1.000000,0.500000
12,"(Telur, Minyak)",(Beras),0.500,0.800000,0.400000
13,(Beras),"(Telur, Minyak)",0.500,0.666667,0.333333
14,(Telur),"(Beras, Minyak)",0.500,0.666667,0.333333
15,(Minyak),"(Beras, Telur)",0.500,0.666667,0.333333
16,"(Beras, Topi)",(Minyak),0.250,1.000000,0.250000
17,"(Topi, Minyak)",(Beras),0.250,0.666667,0.166667
18,(Topi),"(Beras, Minyak)",0.250,0.666667,0.166667
19,"(Beras, Topi)",(Telur),0.250,1.000000,0.250000
20,"(Telur, Topi)",(Beras),0.250,1.000000,0.250000
21,(Topi),"(Beras, Telur)",0.250,0.666667,0.166667
22,"(Buku, Telur)",(Minyak),0.250,1.000000,0.250000
23,"(Buku, Minyak)",(Telur),0.250,0.666667,0.166667
24,"(Telur, Topi)",(Minyak),0.250,1.000000,0.250000
25,"(Minyak, Topi)",(Telur),0.250,0.666667,0.166667
26,(Topi),"(Telur, Minyak)",0.250,0.666667,0.166667
27,"(Beras, Telur, Topi)",(Minyak),0.250,1.000000,0.250000
28,"(Beras, Minyak, Topi)",(Telur),0.250,1.000000,0.250000
29,"(Topi, Telur, Minyak)",(Beras),0.250,1.000000,0.250000
30,"(Beras, Topi)","(Telur, Minyak)",0.250,1.000000,0.250000
31,"(Telur, Topi)","(Beras, Minyak)",0.250,1.000000,0.250000
32,"(Topi, Minyak)","(Beras, Telur)",0.250,0.666667,0.166667
33,(Topi),"(Beras, Telur, Minyak)",0.250,0.666667,0.166667

### Hasil Lift Ratio

Aturan yang digunakan adalah lift ratio >= 1 sehingga melakukan pemangkasan aturan yang dibawah 1

In [72]:
res_sort = res[res['lift'] >= 1]
res_final = res_sort[['antecedents', 'consequents', 'support', 'confidence', 'lift']]
res_final

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,antecedents,consequents,support,confidence,lift
2,(Beras),(Telur),0.625,0.833333,1.111111
3,(Telur),(Beras),0.625,0.833333,1.111111
5,(Buku),(Minyak),0.375,0.750000,1.000000
6,(Telur),(Minyak),0.625,0.833333,1.111111
7,(Minyak),(Telur),0.625,0.833333,1.111111
8,(Topi),(Minyak),0.375,1.000000,1.333333
10,"(Beras, Telur)",(Minyak),0.500,0.800000,1.066667
11,"(Beras, Minyak)",(Telur),0.500,1.000000,1.333333
12,"(Telur, Minyak)",(Beras),0.500,0.800000,1.066667
13,(Beras),"(Telur, Minyak)",0.500,0.666667,1.066667
14,(Telur),"(Beras, Minyak)",0.500,0.666667,1.333333
15,(Minyak),"(Beras, Telur)",0.500,0.666667,1.066667
16,"(Beras, Topi)",(Minyak),0.250,1.000000,1.333333
18,(Topi),"(Beras, Minyak)",0.250,0.666667,1.333333
19,"(Beras, Topi)",(Telur),0.250,1.000000,1.333333
20,"(Telur, Topi)",(Beras),0.250,1.000000,1.333333
21,(Topi),"(Beras, Telur)",0.250,0.666667,1.066667
22,"(Buku, Telur)",(Minyak),0.250,1.000000,1.333333
24,"(Telur, Topi)",(Minyak),0.250,1.000000,1.333333
26,(Topi),"(Telur, Minyak)",0.250,0.666667,1.066667
27,"(Beras, Telur, Topi)",(Minyak),0.250,1.000000,1.333333
28,"(Beras, Minyak, Topi)",(Telur),0.250,1.000000,1.333333
29,"(Topi, Telur, Minyak)",(Beras),0.250,1.000000,1.333333
30,"(Beras, Topi)","(Telur, Minyak)",0.250,1.000000,1.600000
31,"(Telur, Topi)","(Beras, Minyak)",0.250,1.000000,2.000000
32,"(Topi, Minyak)","(Beras, Telur)",0.250,0.666667,1.066667
33,(Topi),"(Beras, Telur, Minyak)",0.250,0.666667,1.333333

# Kesimpulan

Didapatkan 34 Aturan setelah dilakukan aturan asosisasi dimana confidence = 60% dan lift_ratio >= 1. Sehingga Hasil akhir yang didapatkan adalah sebagai berikut!

In [78]:
res_final = res[['antecedents', 'consequents', 'supportxconfidence']]
res_final = res_final.sort_values(by='supportxconfidence', ascending=False)
res_final

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

              antecedents             consequents  supportxconfidence
2                 (Beras)                 (Telur)            0.520833
3                 (Telur)                 (Beras)            0.520833
6                 (Telur)                (Minyak)            0.520833
7                (Minyak)                 (Telur)            0.520833
11        (Beras, Minyak)                 (Telur)            0.500000
12        (Telur, Minyak)                 (Beras)            0.400000
10         (Beras, Telur)                (Minyak)            0.400000
8                  (Topi)                (Minyak)            0.375000
0                 (Beras)                (Minyak)            0.333333
1                (Minyak)                 (Beras)            0.333333
15               (Minyak)          (Beras, Telur)            0.333333
14                (Telur)         (Beras, Minyak)            0.333333
13                (Beras)         (Telur, Minyak)            0.333333
5                  (Buku)                (Minyak)            0.281250
31          (Telur, Topi)         (Beras, Minyak)            0.250000
16          (Beras, Topi)                (Minyak)            0.250000
30          (Beras, Topi)         (Telur, Minyak)            0.250000
19          (Beras, Topi)                 (Telur)            0.250000
20          (Telur, Topi)                 (Beras)            0.250000
29  (Topi, Telur, Minyak)                 (Beras)            0.250000
22          (Buku, Telur)                (Minyak)            0.250000
28  (Beras, Minyak, Topi)                 (Telur)            0.250000
24          (Telur, Topi)                (Minyak)            0.250000
27   (Beras, Telur, Topi)                (Minyak)            0.250000
26                 (Topi)         (Telur, Minyak)            0.166667
32         (Topi, Minyak)          (Beras, Telur)            0.166667
17         (Topi, Minyak)                 (Beras)            0.166667
25         (Minyak, Topi)                 (Telur)            0.166667
23         (Buku, Minyak)                 (Telur)            0.166667
21                 (Topi)          (Beras, Telur)            0.166667
18                 (Topi)         (Beras, Minyak)            0.166667
9                  (Topi)                 (Telur)            0.166667
4                  (Topi)                 (Beras)            0.166667
33                 (Topi)  (Beras, Telur, Minyak)            0.166667